db_user: taskcafe
db_password: taskcafe_test
db_name: taskcafe

postgresql_listen_addresses: "*"
postgresql_max_connections: 300
postgresql_wal_level: "hot_standby"
postgresql_hot_standby: "on"
postgresql_statement_timeout: 60000
postgresql_log_lock_waits: "on"
postgresql_log_destination: "csvlog"
postgresql_log_min_duration_statement: 0
postgresql_users:
  - name: "{{ db_user }}"
    pass: "{{ db_password }}"
postgresql_databases:
  - name: "{{ db_name }}"
    owner: "{{ db_user }}"  
postgresql_pg_hba_custom:
  - {type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5" }

postgresql_user_privileges:
  - name: "{{ db_user }}"                   # user name
    db: "{{ db_name }}"                  # database
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB",  # role attribute flags