---
#- hosts: nfs-server
#  become: yes
#  roles:
#    - nfs-server

- hosts: psql
  become: yes
  roles:
    - psql

- hosts: load-balancer
  become: yes
  roles:
    - load-balancer

- hosts: jenkins
  become: yes
  roles:
    - jenkins

- hosts: jenkins-agent
  become: yes
  roles:
    - jenkins-agent
