---
- hosts: psql
  become: yes
  vars_files:
    - group_vars/psql.yml
  roles: 
    - role: anxs.postgresql

- hosts: app-server
  become: yes
  roles:
    - app-server

- hosts: load-balancer
  become: yes
  roles:
    - load-balancer

- hosts: jenkins
  become: yes
  roles:
    - jenkins
