---
    - name: install go
      ansible.builtin.import_role:
        name: abdennour.golang
      become: yes
      vars:
        golang_version: "1.15.1"

    - name: install redis deps
      yum: name={{item}} state=present
      with_items:
       - make
       - wget
       - epel-release
       - redis
       - git
      tags: redis
      
    - name: run redis
      shell: redis-server --daemonize yes

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/panasyg/tc_binary.git'
        dest: /dist
        force: yes

    - name: Give permissions to an existing file
      ansible.builtin.file:
        path: "{{ t_home }}/taskcafe"
        owner: root
        group: root
        mode: '755'

    - name: enable "{{ port }}"
      firewalld:
        zone: public
        port: "{{ port }}/tcp"
        permanent: true
        state: enabled
      become: yes

    # - name: Send nginx load balancer configuration
    #   template:
    #     src: .env.j2
    #     dest: /dist/.env

    - name: Send nginx load balancer configuration
      template:
        src: cfg.toml.j2
        dest: /dist/cfg.toml

    - name: start app
      ansible.builtin.command: "{{ t_home }}/taskcafe web --config cfg.toml" 