---
    - name: install go
      ansible.builtin.import_role:
        name: abdennour.golang
      become: yes
      vars:
        golang_version: "1.15.1"

    - name: install redis deps
      yum: name={{item}} state=present
      with_items:
       - make
       - wget
       - epel-release
       - redis
       - git
      tags: redis
      
    - name: run redis
      shell: redis-server --daemonize yes

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/panasyg/tc_binary.git'
        dest: /dist

    - name: Give permissions to an existing file
      ansible.builtin.file:
        path: "{{ t_home }}"
        owner: root
        group: root
        mode: '755'

    - name: start app
      ansible.builtin.command: "{{ t_home }}  web" 