---
    - name: install go
      ansible.builtin.import_role:
        name: abdennour.golang
      become: yes
      vars:
        golang_version: "1.15.1"

    - name: install redis deps
      yum: name={{item}} state=present
      with_items:
       - make
       - wget
       - epel-release
       - redis
      tags: redis
      
    - name: run redis
      shell: redis-server --daemonize yes

    - name: download binary executable
      ansible.builtin.command: wget https://files.fm/u/rq79r4qv5 -O "{{ t_home }}" 

    - name: Give permissions to an existing file
      ansible.builtin.file:
        path: "{{ t_home }}"
        owner: root
        group: root
        mode: '755'

    - name: start app
      ansible.builtin.command: "{{ t_home }}  web" 