---
    - name: install go
      ansible.builtin.import_role:
        name: abdennour.golang
      become: yes
      vars:
        golang_version: "1.15.1"
       
    # - name: Download binary from google drive
    #   ansible.builtin.get_url:
    #     url: "https://drive.google.com/uc?export=download&id=184-NI_GsCI7ztOligcleDLCTCfSLxfej"
    #     dest: /dist/taskcafe
    #     checksum: "sha256:https://drive.google.com/uc?export=download&id=184-NI_GsCI7ztOligcleDLCTCfSLxfej"
    #     mode: u=r,g-r,o=r
    - name: install epel-release
      yum: name=epel-release state=present
    
    - name: install PIP
      yum: name=python-pip state=present

    - name: install PIP
      pip: name=gdown state=present

    - name: download file
      ansible.builtin.command: /usr/local/bin/gdown --id 184-NI_GsCI7ztOligcleDLCTCfSLxfej   
      dest: /dist

    - name: install redis deps
      yum: name={{item}} state=present
      with_items:
       - make
       - gcc
       - wget
      tags: redis

    - name: download redis source
      shell: wget -O - http://download.redis.io/releases/redis-{{redis.version}}.tar.gz | tar -xz -C /tmp creates=/tmp/redis-{{redis.version}}
      tags: redis

    - name: install redis
      shell: make chdir=/tmp/redis-{{redis.version}} creates=/tmp/redis-{{redis.version}}/src/redis-server
      tags: redis

    - name: move compiled redis binaries
      shell: cp -f {{item}} /usr/local/bin chdir=/tmp/redis-{{redis.version}}/src
      with_items:
       - redis-cli
       - redis-server
       - redis-benchmark
      tags: redis
      
    - name: run redis
      shell: redis-server --daemonize yes
 
    - name: start app
      ansible.builtin.command: /dist/taskcafe web