---
    - name: update yum
      yum:
        update_cache: yes
        
    - name: installing dependencies for an agent
      yum:
        name: 
          - java-11-openjdk
          - git
        state: present
