---
    - name: Update yum
      yum:
        update_cache: yes
    - name: Install nginx
      yum:
        name: 
          - dnf
          - epel-release
          - nginx
        state: present

    - name: Create nginx configuration directory
      file:
        path: /etc/nginx/conf.d
        state: directory
    - name: Send nginx load balancer configuration
      template:
        src: load_balancer.conf.j2
        dest: /etc/nginx/conf.d/load_balancer.conf
      vars:
        app1_ip: ip1
        app2_ip: ip2
    - name: accept traffic to 8080
      shell: firewall-cmd --zone=public --add-port=8080/tcp --permanent
    - name: reload firewall
      shell: firewall-cmd --reload
    - name: allow http traffic
      shell: setsebool -P httpd_can_network_connect 1
    - name: Restart nginx
      service: name=nginx state=restarted enabled=yes