---
    - name: Install pip
      yum:
        name: python3-pip
        state: present
    - name: install setuptools
      yum:
        name: python3-setuptools
        state: latest
    - name: Install PyMySQL
      pip:
        name: PyMySQL
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: add mariadbrepo for new version
      get_url:
        url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
        dest: /home
    - name: download mariadbrepo to yum
      shell: bash /home/mariadb_repo_setup --mariadb-server-version=10.6
    - name: update yum
      yum:
        update_cache: yes
    - name: Install MariaDB
      yum:
        name: mariadb-server
        state: present
    - name: install mariadb-client
      yum:
        name: MariaDB-client
        state: present
    - name: Start MariaDB
      service:
        name: mariadb
        state: started
    - name: Set MariaDB bind address
      lineinfile:
        path: /etc/my.cnf.d/server.cnf
        line: "bind-address=0.0.0.0"
        state: present
    - name: enable access to port 3306
      shell: firewall-cmd --zone=public --add-port=3306/tcp --permanent
    - name: reload firewall
      shell: firewall-cmd --reload
    - name: remove old conf file
      file:
        path: /etc/my.cnf
        state: absent
    - name: copy conf template
      template:
        src: my.cnf.j2
        dest: /etc/my.cnf
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
    - name: Create database
      mysql_db:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{ mariadb_database }}"
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: create mariadb user
      mysql_user:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_password }}"
        host: "%"
        priv: "*.*:ALL"
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: grant all privileges to mariadb user
      mysql_user:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{ mariadb_user }}"
        priv: "{{ mariadb_database }}.*:ALL"
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: reload mariadb
      service:
        name: mariadb
        state: restarted
